version: '3'

services:
  openserp:
    container_name: serp
    build:
      context: .
    ports: 
      - 8080:8080
    command: serve -l
    #volumes:
    #  - ./config.yaml:/usr/src/app/config.yaml
    environment:
      OPENSERP_APP_HOST: "0.0.0.0"
      OPENSERP_APP_PORT: 8080
      OPENSERP_BAIDU_RATE_REQUESTS: 100000   # Number of requests per Minute
      OPENSERP_BAIDU_RATE_BURST: 200000      # Number of non-ratelimited requests per Minute
    